import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Button from "react-bootstrap/Button";
import FinalVotesList from "../compontents/FinalVotes";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <div className="bg-blue-1">
      <Head>
        <title>Shit Screen</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="container flex justify-between">
        <h1 className="my-5 mx-3 text-5xl text-amber-900 text-center">
          Shit Screen
        </h1>
        {session ? (
          <Button
            onClick={() => signOut()}
            className="text-blue-700 text-2xl justify-self-end my-5"
          >
            Sign Out
          </Button>
        ) : (
          <Button
            onClick={() => signIn()}
            className="text-blue-700 text-2xl justify-self-end"
          >
            Login
          </Button>
        )}
      </header>

      <main className="container">
        <Container className="bg-blue-1">
          <Row>
            <Col>
              <div className="container">
                <h3>Finals</h3>
                <FinalVotesList />
              </div>
            </Col>

            <Col>
              <section className=" bg-blue-3 w-11/12 h-4/5 m-5 p-5">
                <h3>Choose Your Movie</h3>
                <ol>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                  <li>movie</li>
                </ol>
              </section>
            </Col>

            <Col>
              <section className="bg-blue-2 m-5"></section>
            </Col>
          </Row>
        </Container>
      </main>
    </div>
  );
};

export default Home;
